version: 2
jobs:
  build: 
    working_directory: ~/git-chat
    docker: 
      - image: circleci/node:4.8.2 
      - image: mongo:3.4.4 
    steps: 
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-node-new
          command: 'sudo npm install -g n; sudo n stable'
      - run:
          name: install-npm-wee
          command: 'sudo npm install'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: mongo-start
          command: 'npm run mongo'
      - run: # run tests
          name: test
          command: npm test
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
